### PR TITLE
fix: build with Python==3.11

### PR DESCRIPTION
**Pull request by ghost**
Recompile minepy/mine.pyx to fix build with Python==3.11

relative issues
https://github.com/minepy/minepy/issues/37
https://github.com/minepy/minepy/issues/39

### CODE REVIEW

**Comment by batbat99** [comment]
Thank you!
That fixed the build errors for me.

**Comment by QINLEITAN** [comment]
minepy/mine.c:10576:5: error: incomplete definition of type 'struct _frame'
    __Pyx_PyFrame_SetLineNumber(py_frame, py_line);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
minepy/mine.c:438:62: note: expanded from macro '__Pyx_PyFrame_SetLineNumber'
  #define __Pyx_PyFrame_SetLineNumber(frame, lineno)  (frame)->f_lineno = (lineno)
                                                      ~~~~~~~^
/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/pytypedefs.h:22:16: note: forward declaration of 'struct _frame'
typedef struct _frame PyFrameObject;

**Comment by STEVENTAN100** [comment]
hello, could you please tell me which version of vsbuildtool you are using? I encounter error log like this:
```
minepy/mine.c(11420): error C2039: "exc_type": 不是 "_err_stackitem" 的成员
E:\miniconda3\envs\torch\include\cpython/pystate.h(55): note: 参见“_err_stackitem”的声明
minepy/mine.c(11420): error C2039: "exc_type": 不是 "_err_stackitem" 的成员
E:\miniconda3\envs\torch\include\cpython/pystate.h(55): note: 参见“_err_stackitem”的声明
minepy/mine.c(11434): error C2039: "exc_type": 不是 "_err_stackitem" 的成员
E:\miniconda3\envs\torch\include\cpython/pystate.h(55): note: 参见“_err_stackitem”的声明
minepy/mine.c(11436): error C2039: "exc_traceback": 不是 "_err_stackitem" 的成员
E:\miniconda3\envs\torch\include\cpython/pystate.h(55): note: 参见“_err_stackitem”的声明
minepy/mine.c(11450): error C2039: "exc_type": 不是 "_err_stackitem" 的成员
E:\miniconda3\envs\torch\include\cpython/pystate.h(55): note: 参见“_err_stackitem”的声明
minepy/mine.c(11452): error C2039: "exc_traceback": 不是 "_err_stackitem" 的成员
E:\miniconda3\envs\torch\include\cpython/pystate.h(55): note: 参见“_err_stackitem”的声明
minepy/mine.c(11453): error C2039: "exc_type": 不是 "_err_stackitem" 的成员
E:\miniconda3\envs\torch\include\cpython/pystate.h(55): note: 参见“_err_stackitem”的声明
minepy/mine.c(11455): error C2039: "exc_traceback": 不是 "_err_stackitem" 的成员
E:\miniconda3\envs\torch\include\cpython/pystate.h(55): note: 参见“_err_stackitem”的声明
minepy/mine.c(11512): error C2039: "exc_type": 不是 "_err_stackitem" 的成员
E:\miniconda3\envs\torch\include\cpython/pystate.h(55): note: 参见“_err_stackitem”的声明
minepy/mine.c(11514): error C2039: "exc_traceback": 不是 "_err_stackitem" 的成员
E:\miniconda3\envs\torch\include\cpython/pystate.h(55): note: 参见“_err_stackitem”的声明
minepy/mine.c(11515): error C2039: "exc_type": 不是 "_err_stackitem" 的成员
E:\miniconda3\envs\torch\include\cpython/pystate.h(55): note: 参见“_err_stackitem”的声明
minepy/mine.c(11517): error C2039: "exc_traceback": 不是 "_err_stackitem" 的成员
E:\miniconda3\envs\torch\include\cpython/pystate.h(55): note: 参见“_err_stackitem”的声明
minepy/mine.c(13194): warning C4191: “类型强制转换”: 从“PyCFunction”到“void (__cdecl *)(void)”的不安全转换
        使用结果指针进行函数调用可能会导致程序失败
minepy/mine.c(13194): warning C4191: “类型强制转换”: 从“void (__cdecl *)(void)”到“_PyCFunctionFastWithKeywords”的不安全转换
        使用结果指针进行函数调用可能会导致程序失败
minepy/mine.c(13219): warning C4191: “类型强制转换”: 从“PyCFunction”到“void (__cdecl *)(void)”的不安全转换
        使用结果指针进行函数调用可能会导致程序失败
minepy/mine.c(13219): warning C4191: “类型强制转换”: 从“void (__cdecl *)(void)”到“PyCMethod”的不安全转换
        使用结果指针进行函数调用可能会导致程序失败
minepy/mine.c(13601): error C2037: “f_lineno”的左侧部分指定未定义的结构/联合“_frame”
minepy/mine.c(14869): warning C4668: 没有将“_MSV_VER”定义为预处理器宏，用“0”替换“#if/#elif”
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```

**Comment by ghost** [comment]
>  Windows systems are not supported. Use the mictools docker image https://hub.docker.com/r/minepy/mictools/.

_Originally posted by @davidealbanese in https://github.com/minepy/minepy/issues/20#issuecomment-499893634_

**Comment by STEVENTAN100** [comment]
> > Windows systems are not supported. Use the mictools docker image https://hub.docker.com/r/minepy/mictools/.
> 
> _Originally posted by @davidealbanese in [#20 (comment)](https://github.com/minepy/minepy/issues/20#issuecomment-499893634)_

Fine, thanks! I've already change my python==3.10 to solve the problem.

**Comment by ghost** [comment]
I will close this pull request. 

The solution is just simply run the [compile_pyx.sh](https://github.com/minepy/minepy/blob/master/compile_pyx.sh) script and recompile the code on your own when using a newer version of Python.

**Comment by MikeB2019x** [comment]
> Fine, thanks! I've already change my python==3.10 to solve the problem.

Changing to 3.10 did not solve this problem for me.  Looks like if doing a pip install doesn't work, you have to download the repo and then recompile?

**Comment by Nirvana2211** [comment]
> I will close this pull request.
> 
> The solution is just simply run the [compile_pyx.sh](https://github.com/minepy/minepy/blob/master/compile_pyx.sh) script and recompile the code on your own when using a newer version of Python.

This solution doesn't worked on linux. 

./compile_pyx.sh

performance hint: minepy/mine.pyx:95:28: Exception check after calling '_free_score' will always require the GIL to be acquired.
Possible solutions:
        1. Declare '_free_score' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
        2. Use an 'int' return type on '_free_score' to allow an error code to be returned.
